/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.loadWellData;

import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class MantPpal extends javax.swing.JDialog{

    /**
     * Creates new form MantPpal
     */
    public static final int AGREGAR = 0;
    public static final int MODIFICAR = 1;
    public static final int ELIMINAR = 2;
    public static final int AFTER_UPDATE = 3;    
    public static final int AFTER_DELETE = 4;  
    public static final int NADA=-1;
    
    public int accion=NADA;
    
    public Object[] ob_array = null;
    
    public static final int ancho=132;
    public static final int alto=115;
    
    public Numeros oNumeros=new Numeros();
   
    public MantPpal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.jButtonProcesar.setVisible(false);
        this.jButtonCancelar.setVisible(false);
    }

    public void msgbox(String s){
        JOptionPane.showMessageDialog(null, s);        
    }
    public boolean msgboxYesNo(String s) {
        int respuesta=JOptionPane.DEFAULT_OPTION;
        boolean returnVal=false;
        respuesta=JOptionPane.showConfirmDialog(null,
            s, "", JOptionPane.YES_NO_OPTION);
        if (respuesta==JOptionPane.YES_OPTION) {
            returnVal=true;
        }
        return returnVal;
    }
    
    public Double dameDoble(javax.swing.JFormattedTextField f){
        Double r=0.0;
        Object o=f.getValue();
        if (o==null) return 0.0;
        String t=o.getClass().getSimpleName();
        if ("Double".equals(t)) {
           r=(Double) o;
        }
        if ("Long".equals(t)) {
           r=new Double((Long)o); 
        }
        return r;
    }
    
    public Long dameLong(javax.swing.JFormattedTextField f){
        Long r=new Long(0);
        Object o=f.getValue();
        if (o==null) return new Long(0);
        String t=o.getClass().getSimpleName();
        if ("Long".equals(t)) {
           r=(Long) o;
        }
        if ("Double".equals(t)) {
           r=Long.parseLong(o.toString()); 
        }
        return r;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonProcesar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 450));
        setModal(true);
        setResizable(false);

        jButtonProcesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/loadWellData/check.png"))); // NOI18N
        jButtonProcesar.setToolTipText("Procesar");
        jButtonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcesarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/loadWellData/delete.png"))); // NOI18N
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/loadWellData/add.png"))); // NOI18N
        jButtonAgregar.setToolTipText("Agregar registro");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/loadWellData/update.png"))); // NOI18N
        jButtonModificar.setToolTipText("Modificar informacion existente");
        jButtonModificar.setEnabled(false);
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/loadWellData/delete_2.png"))); // NOI18N
        jButtonEliminar.setToolTipText("Eliminar registro");
        jButtonEliminar.setEnabled(false);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        accion=AGREGAR;
        setearControles();
        agregar();
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    public void agregar() {
        
    }
    
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        accion=NADA;
        setearControles();
        cancelar();
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed
    
    public void setearControles(){
        switch (accion) {
            case AGREGAR:
                this.jButtonAgregar.setEnabled(false); 
                this.jButtonModificar.setEnabled(false);
                this.jButtonEliminar.setEnabled(false);
                this.jButtonProcesar.setVisible(true);
                this.jButtonCancelar.setVisible(true);
                break;
            case MODIFICAR:
                this.jButtonAgregar.setEnabled(false); 
                this.jButtonModificar.setEnabled(false);
                this.jButtonEliminar.setEnabled(false);
                this.jButtonProcesar.setVisible(true);
                this.jButtonCancelar.setVisible(true);
                break;
            case ELIMINAR:
                this.jButtonAgregar.setEnabled(false); 
                this.jButtonModificar.setEnabled(false);
                this.jButtonEliminar.setEnabled(false);
                this.jButtonProcesar.setVisible(true);
                this.jButtonCancelar.setVisible(true);
                break;
            case NADA:
                this.jButtonAgregar.setEnabled(true); 
                this.jButtonModificar.setEnabled(false);
                this.jButtonEliminar.setEnabled(false);
                this.jButtonProcesar.setVisible(false);
                this.jButtonCancelar.setVisible(false);
                break;
            case AFTER_UPDATE:
                this.jButtonAgregar.setEnabled(true); 
                this.jButtonModificar.setEnabled(true);
                this.jButtonEliminar.setEnabled(true);
                this.jButtonProcesar.setVisible(false);
                this.jButtonCancelar.setVisible(false);
                break;
            case AFTER_DELETE:
                this.jButtonAgregar.setEnabled(true); 
                this.jButtonModificar.setEnabled(true);
                this.jButtonEliminar.setEnabled(true);
                this.jButtonProcesar.setVisible(false);
                this.jButtonCancelar.setVisible(false);
                break;
                
        }
    }
    
    public void soloDobles(java.awt.event.KeyEvent evt) {
        char inputChar=evt.getKeyChar();
//        if (inputChar=='.') {
//            evt.setKeyChar(','); 
//        } else
        if ((inputChar>'9' | inputChar <'0') & inputChar!='.') {
            evt.setKeyChar('\b');
        }         
    }
    
    public void soloEnteros(java.awt.event.KeyEvent evt) {
        char inputChar=evt.getKeyChar();
        if ((inputChar>'9' | inputChar <'0')) {
            evt.setKeyChar('\b');
        }         
    }
    
    private void jButtonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcesarActionPerformed
        procesar();
    }//GEN-LAST:event_jButtonProcesarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
       
        accion=MODIFICAR;
        setearControles();
        modificar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        accion=ELIMINAR;
        setearControles();
        eliminar();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    public void eliminar() {
        
    }
    
    public void modificar() {
        
    }
    
    public void procesar() {
        
    }
    
    public void cancelar() {
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MantPpal dialog = new MantPpal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAgregar;
    public javax.swing.JButton jButtonCancelar;
    public javax.swing.JButton jButtonEliminar;
    public javax.swing.JButton jButtonModificar;
    public javax.swing.JButton jButtonProcesar;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
